Skip preflight check
I don't think this is a huge risk. The error below only came about
because in the madliberation project madliberationjs lives inside a
project (madliberation) with its own package.json. It's not like I
package the two together.

Here is the error this is attempting to fix:

> react-scripts build

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to
fix locally.

The react-scripts package provided by Create React App requires a
dependency:

  "jest": "26.6.0"

Don't try to install it manually: your package manager does it
automatically.
However, a different version of jest was detected higher up in the tree:

  /home/runner/work/madliberation/madliberation/node_modules/jest
(version: 26.6.3)

Manually installing incompatible versions is known to cause
hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true
to an .env file in your project.
That will permanently disable this message but you might encounter other
issues.

To fix the dependency tree, try following the steps below in the exact
order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in
your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "jest" from dependencies and/or devDependencies in the
package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the
above steps with it instead.
     This may help because npm has known issues with package hoisting
which may get resolved in future versions.

  6. Check if
/home/runner/work/madliberation/madliberation/node_modules/jest is
outside your project directory.
     For example, you might have accidentally installed something in
your home folder.

  7. Try running npm ls jest in your project folder.
     This will tell you which other package (apart from the expected
react-scripts) installed jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in
your project.
That would permanently disable this preflight check in case you want to
proceed anyway.

P.S. We know this message is long but please read the steps above :-) We
hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! madliberationjs@0.0.1 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the madliberationjs@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-12-15T01_05_11_437Z-debug.log
Makefile:37: recipe for target 'build-frontend' failed
make: *** [build-frontend] Error 1
Error: Process completed with exit code 2.